### ISSUE TITLE
ios 13.4 - orientation issue

### ISSUE THREAD

**Issue by merri-ment** [MikeKovarik/exifr#25]
Hey there,

I noticed iOS has changed the way it manages orientation in 13.4, the issue can be observed in your orientation example.

I have attached an image illustrating the issue, 
on the left iOS 13.3 working as expected across the canvas row.
on the right iOS 13.4 the orientation readings from exifr are returning correctly, however ios now appear to auto-rotate the image for you when it is drawn into the canvas.

<img width="928" alt="Screen Shot 2020-04-08 at 11 58 06 PM" src="https://user-images.githubusercontent.com/52738506/78781813-066d5b80-79f5-11ea-9291-e289752e7fbf.png">

**Comment by MikeKovarik** [comment]
Hello, thanks for posting this.
I had some limited knowledge of safari doing something like this regarding correcting orientation. But this change of behavior in 13.4 is news to me.

I didn't yet get around addressing this yet and I can't even debug the new 13.4. I can only get my hands on 13.2 through browserstack.

Though I'm not sure what to do about this. The library keeps parsing the orientation tag correctly so only faulty thing here is the demo.
I was already thinking of adding second argument `accountForAutoRotate` to `exifr.orientation()`. But prior to 13.4 the orientation was still needed for rotating in canvas. So I couldn't correctly tell "do/don't rotate" without knowing the means (canvas / css transform rotate).

Only thing I believe can be done is adding new api. Something like `exifr.rotate()` which would return one of the objects from `manipulations` array (in the example) plus additional boolean properties `canvas` and `css` stating "you can apply this rotation if you use canvas/css".

What do you think?

**Comment by MikeKovarik** [comment]
So I've implemented `exifr.rotation()` and just released 5.0.0
