### ISSUE TITLE
HEIC file parsing error

### ISSUE THREAD

**Issue by mshgh** [MikeKovarik/exifr#38]
Can be after the 2nd fix for https://github.com/MikeKovarik/exifr/issues/35 the new version was released with old code too?
I have use-case when I want to extract EXIF from file located on disk like `await exifr.parse('/tmp/issue-exifr-35.heic', true)` and it is failing for me. Even with the file you added into your tests.

**Comment by MikeKovarik** [comment]
Ugh. Yes. That's highly likely :D I'm sorry. There's been a lot on my plate lately and I must've forgot a few steps during publishing. I'll try to rerelease when I get back from vacation

**Comment by mshgh** [comment]
No worries 😉
BTW have you considered to add support for parsing exif data from streams? Something like the pseudo code below?
Challenge here is you cannot *seek* and you never know how big *chunk* you receive. So simple `seek(123); data = read(456);` becomes *waiting* and *buffering*. And there is no way to *seek* backwards. I assume this is not necessary, but if it is then the whole stream parsing idea is pointless.

This will be useful e.g. in httpServer where you will be able to store stream to a file, calculate hash, and extract exif data all at the same time with minimal memory footprint

```javascript
import { Writable } from 'stream'

function exifPipe(readable, options) {
  return new Promise((resolve, reject) => {
    let exifInfo
    const streamParser = new Writable({
      write(chunk, encoding, callback) {
        // EXIF extraction magic goes here ;)
        // Writable API provides callback so this method can
        // be async, but probably useless for this purpose
      }
    })

    readable
      .pipe(streamParser)
      .on('finish', () => resolve(exifInfo))
      .on('error', reject)
  })
}
```

**Comment by MikeKovarik** [comment]
Hello, so I'm finally releasing new version (with new features), not just a re-release. So I can finally close the issue.

Regarding streams - yes. I have been thinking about this for a while. I'm also thinking about the new web streams (fetch). But it would require a lot more work. I'm happy I was finally able to get png support. Streams will have to wait for now :D
