### ISSUE TITLE
Provide option to receive segment errors as object instead of encoded string

### ISSUE THREAD

**Issue by Projkt-James** [MikeKovarik/exifr#41]
https://github.com/MikeKovarik/exifr/blob/84fdac56e7900301b326bdfd9af2bc6ae48f0f47/src/parser.mjs#L46

In some cases I've found jpg images that will throw error "Segment unreachable: " for the iptc type. Wish to handle a graceful fallback to parsing the buffer again just with iptc flagged false. It would be handy to not have to json.parse the segment object that has been encoded as a string in the linked line. Would you accept a pull request for this options flag change?

**Comment by MikeKovarik** [comment]
Hello. 
Of course I would accept PR 👍 . Though this sounds weird. As far as I know this shouldn't happen unless the file is corrupted. Could you provide me with said jpg? I'd like to look at it myself :)

Btw there's already a silentErrors option set to true by default
https://github.com/MikeKovarik/exifr/blob/master/src/options.mjs#L171
You can continue here.

**Comment by Projkt-James** [comment]
Sure thing, here is an example of two jest unit tests of the same sample image one running "{ iptc: true, xmp: true}" and the second running "{ iptc: false, xmp: true }". My goal is to extract the maximum amount of metadata information possible by handling the iptc segment error and rerunning the buffer through exifr with new flags. Example jpg is part of this example repo here: https://github.com/Projkt-James/exifr-iptc-example

![image](https://user-images.githubusercontent.com/750541/94878361-71798580-04a0-11eb-8b89-db71b2a64f1b.png)

**Comment by MikeKovarik** [comment]
Thank you for filing the bug. And I'm even more grateful for the the image and repo. It helped me greately with fixing the bug.

Later tonight (or throughout the weekend) I'll be pushing the fix (along with png support) and releasing new major version.
