### ISSUE TITLE
Getting icc from image got errors

### ISSUE THREAD

**Issue by vip30** [MikeKovarik/exifr#44]
I am using version 6.0 and seems this image can't retrieve the icc 

it returns the errors
```
message: "Invalid typed array length: 4"
stack: "RangeError: Invalid typed array length: 4↵    at new Uint8Array (<anonymous>)↵    at m.getUint8Array (webpack-internal:///./node_modules/exifr/dist/full.esm.mjs:35:2740)↵    at m.getString (webpack-internal:///./node_modules/exifr/dist/full.esm.mjs:35:2835)↵    at nt.parseTags (webpack-internal:///./node_modules/exifr/dist/full.esm.mjs:35:59863)↵    at nt.parse (webpack-internal:///./node_modules/exifr/dist/full.esm.mjs:35:59427)↵    at eval (webpack-internal:///./node_modules/exifr/dist/full.esm.mjs:35:11508)↵    at Array.map (<anonymous>)↵    at J.doParse (webpack-internal:///./node_modules/exifr/dist/full.esm.mjs:35:11480)↵    at async J.parse (webpack-internal:///./node_modules/exifr/dist/full.esm.mjs:35:11202)"
```

However, it works on https://mutiny.cz/exifr/

here is the image, thanks

https://imgur.com/7J6rgK7

**Comment by MikeKovarik** [comment]
Hello. First of all, I'm sorry for the late response. There's never enough of spare time to dedicate to open source project :(.
Anyway. I tried looking into the issue and I can't replicate it. It either got fixed along other issues or I'm missing some key ingredient to trigger this issue.
Could you please try the latest version, and reopen the issue if it's still failing? Perhaps with the code you're using or more info about the env. Thank you
