### ISSUE TITLE
Date parsing issue when used in Lambda

### ISSUE THREAD

**Issue by flyandi** [MikeKovarik/exifr#45]
I am using exifr as part of an image processor in my lambda - however it seems there are some issues with parsing the correct date of an image. Check it out:

This is what the lambda function responses to when I just do a `(new Date).toISOString()`:

```
2020-10-24T20:22:17.803Z
```

which is correct, now the same when using the parsed exifr O

```
2020-10-24T10:03:23.000Z
```
which is incorrect - well the picture was taken at 10:03AM but that is the Pacific time. I expect it to be 17:03 UTC.

Now when I console.log the parsed values:

```
DateTimeOriginal: 2020-10-24T10:03:23.000Z,
CreateDate: 2020-10-24T10:03:23.000Z,
```

However when I run the same image through the Demo App:

```
"DateTimeOriginal": <Date 2020-10-24T17:03:23.000Z>,
```

Which is correct. So something is up when parsing it through a node lambda process. An ideas?

Also I have no idea where it get the correct offset from. The image doesn't actual have offset information.

**Comment by MikeKovarik** [comment]
Hello. First of all, thanks for using the library.
I didn't look into it yet (cause it's close to midnight in my timezones :D ) so I have no grasp of the problem or any solution. Though I have an idea what might've gotten wrong and answer is better than no answer :D

It seems to me that the lambda is running at different timezone than your browser. You are right that there are no timezone data in the exif. And exifr just calls new Date(...) on whatever string is in the exif. It's not ideal but worked kn 99% cases. :D until now. I'd suggest disabling post processing with options.reviveValues and handling the date on your own from here.

I'm sorry, i have no idea how to fix it on my end right now.

**Comment by flyandi** [comment]
So interesting when I use `reviveValues: false` I am getting actual `DateTimeOriginal: '2020:10:18 17:46:52'` ...  I run a couple more tests on various images and turns out that those values seem to represent the actual time when the photo was taken in whatever timezone (doesn't matter and it is not included). 

I think I confused myself by converting to an UTC timestring and than trying to offset it by the browser's local time. Basically I need to treat this date as-is. 

This is an interesting problem because for an end-user the time will never change. Doesn't matter if you are in California or in Berlin - this image was taken at 5:46PM. I guess that makes sense since many camera systems (incl. drones) don't really include timezone identifiers where you would know it exactly.

I am closing this since it's not a library issues but more of an understanding issue.

**Comment by josephfrazier** [comment]
I'm experiencing a similar [issue](https://github.com/josephfrazier/Reported-Web/issues/316), and I noticed that some images have `OffsetTime`, `OffsetTimeOriginal`, or `OffsetTimeDigitized`. According to https://exiftool.org/TagNames/EXIF.html, these are the offsets for `ModifyDate`, `DateTimeOriginal`, and `CreateDate`. @MikeKovarik, would you be interested in a PR that takes these into account when reviving the Date object?
