### ISSUE TITLE
character encoding issue

### ISSUE THREAD

**Issue by andrisi** [MikeKovarik/exifr#47]
When reading the attached file, accented characters are lost in the IPTC fields and converted to "?" marks. The Windows 10 file info dialog reads them all right. I fixed another IPTC reading package and the problem was somewhere arounf Buffer.slice - reading the file byte-by-byte and then using the char code works ok.

![ferencziektere](https://user-images.githubusercontent.com/1255809/99832373-5817c000-2b58-11eb-9813-9e796d562a6e.jpg)

**Comment by MikeKovarik** [comment]
Hello, thanks for point this out. I am aware that there are multiple encoding types used in various places in exif but I will look into this one specifically and add it to my test suite if you don't mind. Though I cant promise any timeline. I'm busy lately, in the process of automating my home, with wires sticking everywhere :D and I can't just leave it hanging.

**Comment by andrisi** [comment]
Thanks @MikeKovarik good luck with the home automation and let me know if you need help with testing the charset. Ideally one would want to get it in utf-8 I guess - using some other lib to recognise the charset, but the raw data would be fine too. The image above should have the following data:

`{
  object_attribute_reference: '',
  keywords: [
    'Budapest. 5. kerület. Kossuth Lajos utca ; Budapest. 5. kerület. Szabad sajtó út 5-6. ; Budapest. 5. kerület. Március 15. tér. Belvárosi Fõplébániatemplom ; Budapest. 5. kerület. Váci utca 34. Klotild-palota ; Budapest. Erzsébet híd ; villamos vasúti pálya ; építés ; munkás ; népviselet ; utcakép ; 1900-as évek'
  ],
  special_instructions: 'Call Number: 020671',
  by_line_title: [ '[Lerakják a síneket a Hatvani utcában]' ],
  copyright_notice: 'Budapest Picture Archive (Metropolitan Ervin Szabó Library, Budapest) and/or Author. Exact info, order: bpgyujt@fszek.hu'
}`

**Comment by MikeKovarik** [comment]
Hello, I'm happy to say: it's finally fixed.
I'll be publishing 6.1.1 once CI passes.
Thank you for helping out on this.

**Comment by andrisi** [comment]
Thanks! I hope the home automation went well too, and now you're all hands free :-)
