### ISSUE TITLE
<img> elements will be auto rotated on ios Safari browser(since Safari 13.4).

### ISSUE THREAD

**Issue by Elvis007** [MikeKovarik/exifr#50]
What's the difference between '_css_' and '_canvas_' attributes of return obj for the `rotation(file)`.
And how to handle the quirk that `<img>` elements will be auto rotated on ios Safari browser(since Safari 13.4),  but does not alter EXIF.
Is there any way to detect it whether the `<img>` element was rotated?

**Comment by MikeKovarik** [comment]
Hello, sorry for the late response. I'm doing this in my free time of which I unfortunately have very little.
There's utility function exifr.rotation and all your questions are explained in the readme [here](https://github.com/MikeKovarik/exifr#rotationfile).
I've also fixed more quirks quirks regarding desktop safari on mac and it will be available with in the new exifr version.
