### ISSUE TITLE
dates are resolved relative to local time zone

### ISSUE THREAD

**Issue by chriscdn** [MikeKovarik/exifr#51]
I'm trying to use exifr to extract the date of the photo.  However, it seems exifr returns a different result depending on the time zone of the browser.  This is easy to demonstrate:

1. Visit https://mutiny.cz/exifr/
2. Drag a photo into the browser and notice the `DateTimeOriginal` value
3. Change the time zone of the computer
4. Drag the same photo into the browser and notice `DateTimeOriginal` differs.

The same problem happens when using with node.js.

I traced the problem to the `reviveDate` function, which constructs the date as follows:

```
var date = new Date(year, month - 1, day);
```

Check out the [Date constructor documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date), and you'll see this:

> The parameter values are all evaluated against the local time zone, rather than UTC.

I would expect the date to be returned in a format independent of my local time zone.  Unfortunately, I'm not sure how this can be achieved using the Date class since the time zone of the photo is unknown (unless GPS data is available).

I hope this helps you understand and resolve the issue.

**Comment by MikeKovarik** [comment]
Hello. I'm aware of this problem, though it stems from the design of EXIF. It does not store the timezone and thus the parsed `Date` always changes, depending on the device, relative to its timezone.
There's more discussion about it in #45.
Unfortunately I can only advise to turn off transforming the date string to `Date` instance using `reviveDate`
