### ISSUE TITLE
No declare for rotation method

### ISSUE THREAD

**Issue by hi-zhaolei** [MikeKovarik/exifr#52]
Missing the declare of the rotation method in ts type file 

![image](https://user-images.githubusercontent.com/5736062/104849874-183a4280-5927-11eb-830a-068dd7cd340b.png)

![image](https://user-images.githubusercontent.com/5736062/104849893-3142f380-5927-11eb-90d7-39a2de80eff3.png)

**Comment by MikeKovarik** [comment]
Hello, I'm very sorry for handling this so late. The pandemic's fallout has been taking up most of my free time lately.
Fixed this in latest commits and I'll try to publish the fix along with some other issues sometime this week.
