### ISSUE TITLE
read() does not work

### ISSUE THREAD

**Issue by akidee** [MikeKovarik/exifr#53]
Current version on node v.14.10.1

```
'use strict'
const exifr = require('exifr')
, file = process.argv[2]
, exr = new exifr.Exifr()
;(async () => {
	const result = await exr.read(file)
	console.log(result)
})()
```

Output:

    undefined

What am I doing wrong?

**Comment by MikeKovarik** [comment]
Hello. Can you send me the file you're trying to parse. There's a chance it has no exif and the `undefined` output is correct.

**Comment by akidee** [comment]
The file is not the problem. I tested it with several files (TIFF, JPEG) after update to exifr 6.0.0. Replacing

    const result = await exr.read(file)

by

    const result = await exifr.parse(file)

always returns the expected data.

**Comment by akidee** [comment]
Anyway,

    await exr.read(file)
    let result = await exr.parse(file)

works as expected. According to the documentation, `read()` should return an `output`. So what is this output?

**Comment by MikeKovarik** [comment]
So you're using the Exifr class which only accepts file in the read (file) method but then you can choose what to do with it: either parse() or extractThumbnail(). Neither of which accept any argument.

More on this here: https://github.com/MikeKovarik/exifr/blob/master/README.md#exifr-class

But I'd recommend to stick with the high level API https://github.com/MikeKovarik/exifr/blob/master/README.md#usage

**Comment by MikeKovarik** [comment]
One more update. I'm sorry for making a mistake. The example in readme I pointed you to was in fact incorrect. It was some sort of a blindspot I always just glanced over and didn't realize.
The methods work like i said in the previous reply, and the code in readme now reflects that correctly.
