### ISSUE TITLE
Update index.d.ts file for accepting exif in format options

### ISSUE THREAD

**Issue by shriram93** [MikeKovarik/exifr#56]
Instead of `exif` in options interface, its mentioned as `exifif`. Please change the following from,
`	exfif?: FormatOptions | boolean,`
to
`	exif?: FormatOptions | boolean,`

**Comment by MikeKovarik** [comment]
Hello, thanks for pointing this out, I don't know how I missed that :D
I'll try to publish the fix along with some other issues sometime this week.
