### ISSUE TITLE
Binary data / garbage characters extracted from IPTC fields

### ISSUE THREAD

**Issue by sunild** [MikeKovarik/exifr#67]
I'm not sure what this photographer is doing (in Lightroom, I believe) but some of the photos they produce have this problem. Most do not.

I've attached a file here that shows the funky data in the IPTC "Object Name" field. I have 5 other examples, and can share them privately if you like.

I'm not able to speak w/the photographer and can't determine if they are doing something wrong or maybe exifr is. Would you be able to provide some insight?

![binary-data-in-iptc-object-name-field](https://user-images.githubusercontent.com/283872/121734061-1b39f900-caa9-11eb-9814-e8f22c496a77.jpg)

**Comment by sunild** [comment]
One clue I forgot to mention was that in one case this managed to extract so much data that MySQL failed to store it in a TEXT column. That's gotta be a lot of data haha, but kind of sounds like it didn't detect the end of the metadata...

**Comment by sunild** [comment]
We came across more examples of this problem over the weekend. In the past this problem was only w/some images from a particular photographer. This weekend we noticed it happened w/photos from two other photographers.

Here's one example, the garbage data is visible if you upload these photos to your demo page: https://mutiny.cz/exifr/

![binary-data-in-iptc-city-field-2](https://user-images.githubusercontent.com/283872/123832148-e5bf4900-d8b9-11eb-9abb-66d63ec44e6d.jpg)

**Comment by sunild** [comment]
I'm attaching a photo from another photographer, the photo from the other photographer is large to attach here.

![binary-data-in-iptc-sub-location](https://user-images.githubusercontent.com/283872/123833372-210e4780-d8bb-11eb-8b5f-2228c39f1333.jpg)

**Comment by MikeKovarik** [comment]
Hello. thank you for all the photos a info. I tracked down the problem and fixed it. In turn it should also improve IPTC parsing performance. 7.1.1 was just released :)

**Comment by sunild** [comment]
Thank you, that's awesome! 

I am trying to use 7.1.1 but it's not working in my project. I've confirmed the fix is working in your demo, and in my fork of this repo. But for some reason I can't get it work when using the package from npm.

**Comment by MikeKovarik** [comment]
I'm sorry. I messed up. Try 7.1.2

**Comment by sunild** [comment]
Confirming it's working now... Thank for you creating/maintaining such a cool project!
