### ISSUE TITLE
Support for altitude metadata

### ISSUE THREAD

**Issue by NicoNekoru** [MikeKovarik/exifr#69]
The module works very well but the one thing I found that is missing is the altitude information which is in fact in metadata. Other modules are able to grab this information so can `exifr`?

**Comment by MikeKovarik** [comment]
Hello, I dont think I understand. Exifr can parse altitude if it is included in the image. such as in the demo page http://mutiny.cz/exifr/

![image](https://user-images.githubusercontent.com/3995401/122995404-dcaa1580-d3a9-11eb-9a1d-c05aa4192a2d.png)

**Comment by NicoNekoru** [comment]
Agh, I didn't look at the raw data and have been using the `.gps` method which only returns longitude and latitude so I didn't notice. Sorry for the mistake.

**Comment by NicoNekoru** [comment]
Also why isn't the altitude in the `.gps` method?
