### ISSUE TITLE
Cannot read property 'byteLength' of undefined error when using UrlFetcher w/nodejs and the server issues a redirect

### ISSUE THREAD

**Issue by sunild** [MikeKovarik/exifr#73]
I think I've narrowed down the cause of this issue I'm having with reading metadata from images stored in Box.com.

I'll see if I can whip up an example of the problem, but it's a bit involved b/c you need to pass an Authorization header and their auth tokens expire after an hour or so. 

To access files in box, I'm using the custom headers option and passing headers like this:
```
{ Authorization: `Bearer ${boxAccessToken}`, "Content-Type": "application/json" }
```

Then you can pass exifr a URL like this to get the metadata:
```
`https://api.box.com/2.0/files/${boxFileId}/content`
```

I've figured out the following so far:

Stack trace:
```
TypeError: Cannot read property 'byteLength' of undefined
    at Object._readChunk (/Users/USERNAME/exifr/dist/full.umd.js:1:30584)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.readChunked (/Users/USERNAME/exifr/dist/full.umd.js:1:28547)
    at M (/Users/USERNAME/exifr/dist/full.umd.js:1:6098)
    at ue.read (/Users/USERNAME/exifr/dist/full.umd.js:1:12033)
    at Object.ce [as parse] (/Users/USERNAME/exifr/dist/full.umd.js:1:13239)
```

This error is coming from `UrlFetcher.js` lines 23-25:
```
let res = await fetch(this.input, {headers});
let abChunk = await res.arrayBuffer()
let bytesRead = abChunk.byteLength
```

The initial response from the Box API is a 302, so I assume there is no body to read and `abChunk` is undefined.

I'm not quite grokking how the fetch polyfill is working, and if it's possible to make it follow redirects. I had forked your repo last year and hacked it so it was using the actual node-fetch package, and it worked b/c by default node-fetch follows redirects.

Could you give me any pointers on what I might do to address this? I'll happily submit a PR!

Thank you,
Sunil

**Comment by sunild** [comment]
Sorry, turns out I just didn't understand how to make this work w/node-fetch.

In particular, I needed to require node-fetch as shown below before I imported exifr):
```
global.fetch = require('node-fetch');
import exifr from 'exifr';
```

I'm not sure if there's a better way to do this w/typescript, but now it follows the redirects 😎

**Comment by MikeKovarik** [comment]
Hello. I'm sorry, I didn't mean for the shim to be a full-fat replacement for fetch. As you found out, you could provide your own fetch implementation but it isn't very well documented.
Anyway, the redirect wasn't that big of a deal to implement so it should work in 7.1.3 now. But like i said. It's just a simple thing that won't cover all use cases.

**Comment by sunild** [comment]
Thanks for the update, I installed version 7.1.3 and can confirm it's working...
